name: Build to Staging branch
run-name: Build to stage / version ${{ GITHUB_RUN_NUMBER }}-STG
on:
  push:
    branches:
      - master

jobs:

  build-and-push:
    name: Builds the code to Stage

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Get current version
        id: version
        run: echo "::set-output name=current::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER-STG"

      
