name: Build to Staging branch

on:
  push:

env:
  build-number: $(date +'%Y.%m.%d').${{github.run_number}}

jobs:

  build-and-push:
    name: Builds the code and pushes a docker image to ECR

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

run-name: Build code from staging branch / version ${{ github.env.build-number }}
