name: Build to Staging branch

on:
  push:

env:
   - name: Get current version
     id: version
     run: echo "::set-output name=current::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER-STG"

jobs:

  build-and-push:
    name: Builds the code and pushes a docker image to ECR

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.STADION_BOT_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.current }}
          release_name: Release v${{ steps.version.outputs.current }}
          body: |
            TBC - Update 
          draft: false
          prerelease: true


