name: Build to Staging branch

on:
  push:

env:
  build-number: ${{github.run_number}}

jobs:

  build-and-push:
    name: Builds the code and pushes a docker image to ECR

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2


      - name: Get current version
        id: version
        run: echo "::set-output name=current::$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER-STG"      

run-name: Build code from staging branch / version ${{ steps.version.outputs.current }}
