on:
  release:
    types: [released]
    branches:
      - 'Stage'

name: Show release number - Stage

jobs:
  prerelease:
    name: Deploy to Stadion Stage
    runs-on: ubuntu-latest

    steps:
    - name: Show Release Info
      run: |
        echo "Pushing release ${{ secrets.GITHUB_TOKEN }} to Stage"
        
    - name: Trigger update for the Stage service
      run: echo ${GITHUB_REF##*/}
