on:
  release:
    types: [prereleased]

name: Deploy to Stadion Dev test stage

jobs:
  prerelease:
    name: Deploy to Stadion Dev
    runs-on: ubuntu-latest

    steps:

    - name: Trigger update for the Dev service
      run: |
         echo ${GITHUB_REF##*/}
      
